"""initial schema: section 15 data model + PostGIS

Revision ID: 0001
Revises:
Create Date: 2026-08-23

Hand-authored (not autogenerated): no database was available locally to
autogenerate against. Mirrors ``app.models`` exactly - 18 tables, 9 geometry
columns (SRID 4326), VARCHAR(32) enum columns, spatial GiST + non-spatial
indexes. Enum columns are plain ``VARCHAR(32)`` here (the ORM validates enum
values in Python; ``native_enum=False`` means no native PG enum type to manage).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Tables in FK-safe creation order; downgrade drops the reverse.
_TABLES_IN_ORDER = [
    "districts",
    "locations",
    "roles",
    "infrastructure",
    "landslide_incidents",
    "risk_zones",
    "roads",
    "sensor_readings",
    "users",
    "villages",
    "weather_observations",
    "alerts",
    "audit_logs",
    "field_reports",
    "risk_predictions",
    "terrain_data",
    "emergency_priorities",
    "media_assets",
]


def _base_cols() -> list[sa.Column]:
    """Fresh id / created_at / updated_at columns (shared IDMixin + TimestampMixin).

    Returns new Column objects each call — Column instances are single-use and
    cannot be shared across ``create_table`` calls.
    """
    return [
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    ]


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # --- districts -----------------------------------------------------------
    op.create_table(
        "districts",
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("state", sa.String(120), server_default=sa.text("'Sikkim'"), nullable=False),
        sa.Column("code", sa.String(20), nullable=True, unique=True),
        sa.Column(
            "geom",
            Geometry(geometry_type="MULTIPOLYGON", srid=4326, spatial_index=False),
            nullable=True,
        ),
        *_base_cols(),
    )

    # --- locations -----------------------------------------------------------
    op.create_table(
        "locations",
        sa.Column("name", sa.String(200), nullable=True),
        sa.Column("type", sa.String(50), nullable=True),
        sa.Column(
            "geom",
            Geometry(geometry_type="POINT", srid=4326, spatial_index=False),
            nullable=False,
        ),
        *_base_cols(),
    )

    # --- roles ---------------------------------------------------------------
    op.create_table(
        "roles",
        sa.Column("name", sa.String(32), nullable=False, unique=True),
        sa.Column("description", sa.String(255), nullable=True),
        *_base_cols(),
    )

    # --- infrastructure ------------------------------------------------------
    op.create_table(
        "infrastructure",
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("type", sa.String(32), nullable=False),
        sa.Column("criticality", sa.String(20), nullable=True),
        sa.Column("district_id", sa.BigInteger(), sa.ForeignKey("districts.id"), nullable=True),
        sa.Column(
            "geom",
            Geometry(geometry_type="POINT", srid=4326, spatial_index=False),
            nullable=True,
        ),
        *_base_cols(),
    )

    # --- landslide_incidents -------------------------------------------------
    op.create_table(
        "landslide_incidents",
        sa.Column("district_id", sa.BigInteger(), sa.ForeignKey("districts.id"), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(32), nullable=False),
        sa.Column("severity", sa.String(30), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "is_training_label", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "geom",
            Geometry(geometry_type="POINT", srid=4326, spatial_index=False),
            nullable=False,
        ),
        *_base_cols(),
    )

    # --- risk_zones ----------------------------------------------------------
    op.create_table(
        "risk_zones",
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("area_km2", sa.Float(), nullable=True),
        sa.Column(
            "current_risk_level",
            sa.String(32),
            server_default=sa.text("'green'"),
            nullable=False,
        ),
        sa.Column("district_id", sa.BigInteger(), sa.ForeignKey("districts.id"), nullable=True),
        sa.Column(
            "geom",
            Geometry(geometry_type="MULTIPOLYGON", srid=4326, spatial_index=False),
            nullable=True,
        ),
        *_base_cols(),
    )

    # --- roads ---------------------------------------------------------------
    op.create_table(
        "roads",
        sa.Column("name", sa.String(200), nullable=True),
        sa.Column("ref", sa.String(50), nullable=True),
        sa.Column("road_class", sa.String(50), nullable=True),
        sa.Column("importance", sa.String(30), nullable=True),
        sa.Column("district_id", sa.BigInteger(), sa.ForeignKey("districts.id"), nullable=True),
        sa.Column(
            "geom",
            Geometry(geometry_type="MULTILINESTRING", srid=4326, spatial_index=False),
            nullable=True,
        ),
        *_base_cols(),
    )

    # --- sensor_readings -----------------------------------------------------
    op.create_table(
        "sensor_readings",
        sa.Column("location_id", sa.BigInteger(), sa.ForeignKey("locations.id"), nullable=True),
        sa.Column("sensor_type", sa.String(32), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(30), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_simulated", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        *_base_cols(),
    )

    # --- users ---------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("full_name", sa.String(255), nullable=True),
        sa.Column("phone", sa.String(20), nullable=True),
        sa.Column(
            "preferred_language", sa.String(10), server_default=sa.text("'en'"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("role_id", sa.BigInteger(), sa.ForeignKey("roles.id"), nullable=False),
        *_base_cols(),
    )

    # --- villages ------------------------------------------------------------
    op.create_table(
        "villages",
        sa.Column("name", sa.String(160), nullable=False),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("census_code", sa.String(30), nullable=True),
        sa.Column("district_id", sa.BigInteger(), sa.ForeignKey("districts.id"), nullable=True),
        sa.Column(
            "geom",
            Geometry(geometry_type="POINT", srid=4326, spatial_index=False),
            nullable=True,
        ),
        *_base_cols(),
    )

    # --- weather_observations ------------------------------------------------
    op.create_table(
        "weather_observations",
        sa.Column("location_id", sa.BigInteger(), sa.ForeignKey("locations.id"), nullable=True),
        sa.Column("provider", sa.String(50), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rainfall_mm_1h", sa.Float(), nullable=True),
        sa.Column("rainfall_mm_24h", sa.Float(), nullable=True),
        sa.Column("rainfall_mm_72h", sa.Float(), nullable=True),
        sa.Column("antecedent_index", sa.Float(), nullable=True),
        sa.Column("temp_c", sa.Float(), nullable=True),
        sa.Column("humidity_pct", sa.Float(), nullable=True),
        sa.Column("is_simulated", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("raw", postgresql.JSONB(), nullable=True),
        *_base_cols(),
    )

    # --- alerts --------------------------------------------------------------
    op.create_table(
        "alerts",
        sa.Column("risk_zone_id", sa.BigInteger(), sa.ForeignKey("risk_zones.id"), nullable=True),
        sa.Column("created_by", sa.BigInteger(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("severity", sa.String(32), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("languages", postgresql.JSONB(), nullable=True),
        sa.Column("cap_xml", sa.Text(), nullable=True),
        sa.Column("channels", postgresql.JSONB(), nullable=True),
        sa.Column("status", sa.String(32), server_default=sa.text("'draft'"), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        *_base_cols(),
    )

    # --- audit_logs ----------------------------------------------------------
    op.create_table(
        "audit_logs",
        sa.Column("user_id", sa.BigInteger(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("action", sa.String(100), nullable=False),
        sa.Column("entity_type", sa.String(100), nullable=True),
        sa.Column("entity_id", sa.String(64), nullable=True),
        sa.Column("ip_address", sa.String(64), nullable=True),
        sa.Column("user_agent", sa.String(255), nullable=True),
        # Attribute is ``meta`` on the model; DB column is ``metadata``.
        sa.Column("metadata", postgresql.JSONB(), nullable=True),
        *_base_cols(),
    )

    # --- field_reports -------------------------------------------------------
    op.create_table(
        "field_reports",
        sa.Column("reporter_id", sa.BigInteger(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("reporter_type", sa.String(30), nullable=True),
        sa.Column("category", sa.String(32), nullable=False),
        sa.Column("severity", sa.String(30), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(32), server_default=sa.text("'submitted'"), nullable=False),
        sa.Column("cv_classification", postgresql.JSONB(), nullable=True),
        sa.Column("client_uuid", sa.String(64), nullable=True, unique=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "geom",
            Geometry(geometry_type="POINT", srid=4326, spatial_index=False),
            nullable=True,
        ),
        *_base_cols(),
    )

    # --- risk_predictions ----------------------------------------------------
    op.create_table(
        "risk_predictions",
        sa.Column(
            "risk_zone_id", sa.BigInteger(), sa.ForeignKey("risk_zones.id"), nullable=False
        ),
        sa.Column("model_version", sa.String(50), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("risk_level", sa.String(32), nullable=False),
        sa.Column("prediction_window", sa.String(50), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("contributing_factors", postgresql.JSONB(), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_simulated", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        *_base_cols(),
    )

    # --- terrain_data --------------------------------------------------------
    op.create_table(
        "terrain_data",
        sa.Column("risk_zone_id", sa.BigInteger(), sa.ForeignKey("risk_zones.id"), nullable=True),
        sa.Column("slope_deg", sa.Float(), nullable=True),
        sa.Column("aspect_deg", sa.Float(), nullable=True),
        sa.Column("elevation_m", sa.Float(), nullable=True),
        sa.Column("curvature", sa.Float(), nullable=True),
        sa.Column("twi", sa.Float(), nullable=True),
        sa.Column("lithology", sa.String(120), nullable=True),
        sa.Column("land_cover", sa.String(120), nullable=True),
        sa.Column("source", sa.String(120), nullable=True),
        *_base_cols(),
    )

    # --- emergency_priorities ------------------------------------------------
    op.create_table(
        "emergency_priorities",
        sa.Column("risk_zone_id", sa.BigInteger(), sa.ForeignKey("risk_zones.id"), nullable=True),
        sa.Column(
            "field_report_id", sa.BigInteger(), sa.ForeignKey("field_reports.id"), nullable=True
        ),
        sa.Column("road_id", sa.BigInteger(), sa.ForeignKey("roads.id"), nullable=True),
        sa.Column("priority_rank", sa.String(32), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("population_affected", sa.Integer(), nullable=True),
        sa.Column("rationale", postgresql.JSONB(), nullable=True),
        sa.Column("status", sa.String(30), nullable=True),
        *_base_cols(),
    )

    # --- media_assets --------------------------------------------------------
    op.create_table(
        "media_assets",
        sa.Column(
            "field_report_id",
            sa.BigInteger(),
            sa.ForeignKey("field_reports.id"),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(512), nullable=False),
        sa.Column("media_type", sa.String(30), nullable=True),
        sa.Column("content_type", sa.String(100), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("checksum", sa.String(128), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "geom",
            Geometry(geometry_type="POINT", srid=4326, spatial_index=False),
            nullable=True,
        ),
        *_base_cols(),
    )

    # --- non-spatial indexes -------------------------------------------------
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index("ix_users_role_id", "users", ["role_id"])
    op.create_index("ix_villages_district_id", "villages", ["district_id"])
    op.create_index("ix_roads_district_id", "roads", ["district_id"])
    op.create_index("ix_infrastructure_district_id", "infrastructure", ["district_id"])
    op.create_index("ix_risk_zones_district_id", "risk_zones", ["district_id"])
    op.create_index(
        "ix_risk_predictions_zone_valid_to",
        "risk_predictions",
        ["risk_zone_id", "valid_to"],
    )
    op.create_index(
        "ix_weather_observations_location_id", "weather_observations", ["location_id"]
    )
    op.create_index(
        "ix_weather_observations_observed_at", "weather_observations", ["observed_at"]
    )
    op.create_index("ix_terrain_data_risk_zone_id", "terrain_data", ["risk_zone_id"])
    op.create_index("ix_sensor_readings_location_id", "sensor_readings", ["location_id"])
    op.create_index("ix_sensor_readings_recorded_at", "sensor_readings", ["recorded_at"])
    op.create_index(
        "ix_landslide_incidents_district_id", "landslide_incidents", ["district_id"]
    )
    op.create_index("ix_field_reports_reporter_id", "field_reports", ["reporter_id"])
    op.create_index("ix_field_reports_status", "field_reports", ["status"])
    op.create_index("ix_media_assets_field_report_id", "media_assets", ["field_report_id"])
    op.create_index("ix_alerts_risk_zone_id", "alerts", ["risk_zone_id"])
    op.create_index("ix_audit_logs_user_id", "audit_logs", ["user_id"])
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"])

    # --- spatial (GiST) indexes ----------------------------------------------
    for tbl in [
        "districts",
        "villages",
        "roads",
        "infrastructure",
        "locations",
        "risk_zones",
        "landslide_incidents",
        "field_reports",
        "media_assets",
    ]:
        op.create_index(f"idx_{tbl}_geom", tbl, ["geom"], postgresql_using="gist")


def downgrade() -> None:
    # Dropping a table also drops its indexes; reverse FK-safe order.
    for tbl in reversed(_TABLES_IN_ORDER):
        op.drop_table(tbl)
    # PostGIS extension is intentionally left installed.
